import type { DioramaConfig3DWithVideos } from "@/types/diorama";

const BASE_URL = process.env.NEXT_PUBLIC_ASSET_BASE_URL || "";

export const street: DioramaConfig3DWithVideos = {
  glb: `${BASE_URL}/models/glb/street.glb`,
  loaderImage: `${BASE_URL}/icons/dioramas/test_street/street-preview.png`,
  name: "La place du village",
  navigationType: "poi",
  pois: [
    {
      id: "start",
      label: "Vue initiale",
      emptyName: "start",
      icon: `${BASE_URL}/icons/dioramas/test_street/start.png`,
      ambientSound: `${BASE_URL}/sounds/kids_playing.mp3`,
      zoom: 0.5,
      lookAxis: "x",
      minDistance: 1,
      maxDistance: 20,
      minPolarAngle: 0,
      maxPolarAngle: 1.57,
      minAzimuthAngle: -3.14,
      maxAzimuthAngle: 3.14,
      enableZoom: true,
    },
    {
      id: "window",
      label: "Fenêtre appartement",
      emptyName: "window",
      icon: `${BASE_URL}/icons/dioramas/test_street/window.png`,
      ambientSound: `${BASE_URL}/sounds/kids_playing.mp3`,
      zoom: 0.2,
      lookAxis: "x",
      minDistance: 0.05,
      maxDistance: 0.1,
      minPolarAngle: 1,
      maxPolarAngle: 1.57,
      minAzimuthAngle: 1.14,
      maxAzimuthAngle: 2.14,
      enableZoom: true,
      children: [
        {
          id: "apartment",
          label: "Appartement",
          emptyName: "apartment",
          icon: `${BASE_URL}/icons/dioramas/test_street/apartment.png`,
          ambientSound: `${BASE_URL}/sounds/tv_background.mp3`,
          zoom: 0.2,
          lookAxis: "x",
          minDistance: 0.01,
          maxDistance: 0.05,
          minPolarAngle: 1,
          maxPolarAngle: 1.57,
          minAzimuthAngle: 1.14,
          maxAzimuthAngle: 2.14,
          enableZoom: true,
          children: [
            {
              id: "coffre",
              label: "Coffre",
              emptyName: "coffre",
              icon: `${BASE_URL}/icons/dioramas/test_street/coffre.png`,
              ambientSound: `${BASE_URL}/sounds/snoring_guy.mp3`,
              zoom: 0.05,
              lookAxis: "x",
              minDistance: 0.01,
              maxDistance: 0.05,
              minPolarAngle: 1,
              maxPolarAngle: 1.57,
              minAzimuthAngle: 1.14,
              maxAzimuthAngle: 2.14,
              enableZoom: true,
            },
          ],
        },
      ],
    },
    {
      id: "window2",
      label: "Fenêtre appartement 2",
      emptyName: "window2",
      icon: `${BASE_URL}/icons/dioramas/test_street/window.png`,
      zoom: 0.2,
      lookAxis: "x",
      minDistance: 0.05,
      maxDistance: 0.1,
      minPolarAngle: 1,
      maxPolarAngle: 1.57,
      minAzimuthAngle: 3.14,
      maxAzimuthAngle: 4.14,
      enableZoom: true,
    },
  ],
  videos: [
    {
      name: "TVScreen",
      src: `${BASE_URL}/videos/test_street/Cab_Calloway_1933.mp4`,
      materialIndex: 0,
      loop: true,
      muted: true,
    },
    {
      name: "TVScreen2",
      src: `${BASE_URL}/videos/test_street/Cab_Calloway_Minnie.mp4`,
      autoplay: true,
    },
  ],
  lights: [
    {
      type: "ambient",
      color: 0xffe0cc,
      intensity: 0.5,
    },
    {
      type: "spot",
      emptyName: "spot_01",
      color: 0xfff2cc,
      intensity: 0.8,
      distance: 10,
      angle: Math.PI / 4,
      penumbra: 0.3,
    },
    {
      type: "spot",
      emptyName: "spot_02",
      color: 0xfff2cc,
      intensity: 0.05,
      distance: 8,
      angle: Math.PI / 3.5,
      penumbra: 0.5,
    },
  ],
  bulbs: [
    { emptyName: "bulb_01", color: 0xfff2cc, intensity: 2, emissiveIntensity: 1.5, distance: 10 },
    { emptyName: "bulb_02", color: 0xfff2cc, intensity: 1.8, emissiveIntensity: 1.2, distance: 8 },
  ],
  toonOutline: {
    defaultThickness: 0.001,
    defaultColor: [0, 0, 0],
    defaultAlpha: 0.9,
    defaultKeepAlive: true,
  },
};
